# Generated by Django 5.1.6 on 2025-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_category_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='button_label',
            field=models.CharField(default='Order', max_length=100),
        ),
    ]
